# Generated by Django 3.0.4 on 2020-04-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(help_text='The session lot number', max_length=20, verbose_name='Lot')),
                ('expiry', models.CharField(help_text='The expiration date.', max_length=6, verbose_name='Expiry')),
            ],
        ),
        migrations.CreateModel(
            name='SessionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
