# Generated by Django 3.0.4 on 2020-04-03 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_conductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time that the session was created.', verbose_name='Created'),
            preserve_default=False,
        ),
    ]
