# Generated by Django 3.0.4 on 2020-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_conductor', '0004_auto_20200406_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='SessionField',
        ),
    ]
